rvm: 1.9.3
env:
- PUPPET_VERSION=3.7.3
script:
- bundle exec rake lint
- bundle exec rake validate
- bundle exec rake spec
before_deploy:
- bundle exec rake clean
- bundle exec rake set_travis_version
deploy:
  skip_cleanup: true
  provider: puppetforge
  user:
    secure: e2D2/otGjAUtdTX0stl3VH+EHBDToa9dh+JBT7xMWCtUmEzkJiQMWMNrt52tOgqBF88Qc6P58arD7N+g3CeCrubD5RKh0X9kMhAH7GjoxuAQOJr4KXs46SBRQVXjS2+Itbs6h3oOJMH07G9UUirLEbkkD+CP3xZ7KC0rMwzBHXTdJCmdqX4fRLKuPYNsZwNQ8J7SBfn5A1a7zP5Wp+/21W5yfGjNE2M1qBAvfDHelHVUe9TWOB1qliJjEWCR825i5/tFN5RO8yP+5J/e0KaGRDJJg3rXnz2pewEFNOnA2hx7Q3YceXdYicPd6klusZYbw5o87/x3a+zD33zWU9Ww4pQ0WNkJr7bXUWcsn0UHloxHMs1awgc0Nhu7LrztNPnQldYTKNyEwFO5Taav24NvgWRQg1UYe8GWQRl0SvNEoa/A9CmKgUmRflpVUCRgsFUWvUuhlTqzwyHFlntJ+4GtjabqoOtB1hAqmmBuABExBzTxXtl/yTlT1zPzzMbWgCieJ3+L3iLhxkKfuoGKcLWzY3OtTVdDyiDbpHc7uk/O4QbqyNhhwRg7PhhBdwwrhwc0OUYMwpBpe+8FyhOjfnuNz0tooM0KjU0vj00mgsnBN3o6yqcIG6VJEVXYXEIFhoUaYMZfgH0SDarP+hhIJ101FbkeZu95iFMJqfzQezm1hBM=
  password:
    secure: FGMnYTwoX+oJqTjGmR3zyz0rAoZJf3j+87G2zA0lP9t8oQDPnWaP71T0FD/oXm9kvOc956RACac2XjRhOUsRCA4Ysv1PQhsRW8v9y6+KkZRU7glH3JwpVUgmQ3xFwR4DLI2MMuLlDV4ML+SkxOHCcJ/ybtQPbv6I3UrnHrUAjta3U5YMQpZcx+21FWV30TmMQ4/trFZneJRvp08TUCfJ6RGwBCAOt37/MEP5vPRerdxgqzuhKj3KzTKSSF/bcKxMPobVb7js0jBQGo4ORJfbnM7JHG/nSSWythVJ+q6s6iz8zPqd4o1Ak3c5A9mnoBe8hIJc6u0eLehIkBodZFr+8AOwLurVP7MqMsbVTQUtH4zwdB2iOyZ2N1n8N33Ka9Tcd0pjI+Q+rEdiv7qtaA1bMof/bCQSWvTcHft9+sKEG0CNMXUqlbuk01Ema1fpJ86g9tTrCgGStls/sGnyuMtgJBFT8cw7v2xphsmAiOghec9Kqh5ut0IOVIlvklqMgh126aBKi1o610Yce1+NDGJczjiXIjbBbv+0h19kjHS5xLt+Q5Rl7l9ev5eBVW4GKbrKAqSr+hGGihG+4+vvvNFl0dXCv5AKYIEQqW+C/pk5QU4dveYhR7Au9GfpPyPKqYTG0thXsafviiC78Or2elRx+k1YV9GcdGOrpexlodbV54c=
